# Generated by Django 2.0.1 on 2018-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20180322_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='external_id',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
