# Generated by Django 2.0.1 on 2018-04-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('issues', '0007_auto_20180322_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='issue',
        ),
        migrations.AddField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='tag',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
