# Generated by Django 2.0.1 on 2018-04-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_auto_20180403_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
    ]
