# Generated by Django 2.0.1 on 2018-04-06 05:27

from django.db import migrations
import issues.fields
from issues.utils import update_heat_column_migration_factory


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_issue_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='heat',
            field=issues.fields.HeatIndexField(db_index=True, default=1, score_field='score', timestamp_field='created_date'),
        ),
        migrations.RunPython(update_heat_column_migration_factory),
    ]
